FEAT: page 404
naumch1k/one-fall pull request #48
Opened 2024-08-25 15:30 UTC by Yura33-dev

## Description

This PR is draft for 404 page. Pull request requires enhancement: layout without Header, Footer components etc, checking for design compliance and codebase review.

## Task Link

[Figma Design](https://www.figma.com/design/YKZFEj97V6fe8LADQR5lcq/ONE-FALL?node-id=0-1&t=KIcGZoJcYNdj0cfJ-1).

## Changes Made

Added not-found.tsx and not-found.module.css in src/app

2024-08-26 21:11 UTC, naumch1k requested changes
Hey @Yura33-dev, thanks for submitting a pull request!

I'll have to ask you to revisit it as your implementation does not quite match a design (see attached videos).

https://github.com/user-attachments/assets/4c396033-c1b7-4935-83ec-cee9d477849f

https://github.com/user-attachments/assets/b667f0b2-f4cd-4b58-83fb-fb6d113d7451

https://github.com/user-attachments/assets/21665309-ea19-45cb-bef4-f92bbef70d03

- Please make sure section takes all available device view height.
- Whatever way to implement ribbons you choose, please keep them inside section and position them absolutely relative to section. Please, use absolute positioning on all screen widths - not desktop only.
- Please make sure that on smaller screens, the text is positioned above other blocks.

2024-08-26 21:11 UTC, naumch1k commented on src/app/not-found.tsx
> +          <span className={styles.badge}>404 error</span>
@Yura33-dev 👋 This element here looks more like a `h1`, while _"We couldn’t find the page you’re looking for"_ can be `h2` or `p`

2024-08-26 21:11 UTC, naumch1k commented on src/app/not-found.module.css
> +  color: #242424;
@Yura33-dev Please use our defined color variables wherever possible. If there is no such color, please use the RGB format.

2024-08-26 21:11 UTC, naumch1k commented on src/app/not-found.tsx
> +        <div className={styles.decorLine1}>
@Yura33-dev Wouldn't that be easier to export those ribbons as SVGs instead of adding that much markup and also styles?

2024-08-28 18:41 UTC, Yura33-dev commented on src/app/not-found.tsx
> +        <div className={styles.decorLine1}>
You are absolutely right! 😅

2024-09-02 15:53 UTC, Yura33-dev commented
@naumch1k Hey! There is a new commit with updates. Could you check it and please let me know if something else for improvements? Thanks!

2024-09-03 13:39 UTC, naumch1k commented
@Yura33-dev 👋 Great job, thanks!

I am adding more changes and would appreciate your review. I split my changes into a few separate commits to make navigating through what has changed easier. 

1. I moved the `NotFoundError` component out of the `/app` folder.
2. I refactored `RibbonSvg` UI component to return one element at a time and added an optional `className` prop. I only left size and color styles by `RibbonSvg`; positioning is now handled in `NotFoundError.module.css` - a section where those elements are used. I found that a thinner ribbon looks great on all devices 😍, so I removed another SVG.
3. I ensured the section never exceeded the device screen's height and that there was no scrolling by setting the root to `100dvh`.

https://github.com/user-attachments/assets/9b2defe5-276a-4553-ac9a-ef48cb25c4b7

https://github.com/user-attachments/assets/31e024d9-0443-474d-8759-8cf65407a5c6

https://github.com/user-attachments/assets/af406a4a-ba83-4357-b1c4-56934ab897a6

4. I added a max-width limit - `var(--max-content-width)` - for screens wider than `1280px`.

https://github.com/user-attachments/assets/4a1b9688-3243-4d80-901e-83c913a780aa

5. I applied `align-items: flex-start;` to the flex container with a link to prevent unintended stretching and hover effects when hovering outside its visible area.

https://github.com/user-attachments/assets/4deea83c-5866-4631-9c0c-08d4f32f421c

2024-09-04 10:39 UTC, Yura33-dev commented
@naumch1k, Hi! Everything looks fine!

2024-09-04 13:54 UTC, naumch1k approved these changes

2024-09-04 13:54 UTC, merged